/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Koneksi.KoneksiDB;
import com.sun.xml.internal.bind.unmarshaller.Messages;
import java.io.File;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author A3
 */
public class FormMenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form FormMenuUtama
     */
    public FormMenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        lblMenu = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblPelanggan = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblTransaksi = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblWilayah = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnLogin = new javax.swing.JMenu();
        mnLogout = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        MnLapKaryawan = new javax.swing.JMenuItem();
        MnLapPelanggan = new javax.swing.JMenuItem();
        MnLapWilayah = new javax.swing.JMenuItem();
        MnLapMenu = new javax.swing.JMenuItem();
        MnLapDitempat = new javax.swing.JMenuItem();
        MnLapDelivery = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        lblMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/menu.png"))); // NOI18N
        lblMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenuMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Karyawan");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Menu");

        lblPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pelanggan.png"))); // NOI18N
        lblPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPelangganMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Menu Utama Restoran");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Pelanggan");

        lblTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/transaksi.png"))); // NOI18N
        lblTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTransaksiMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Transaksi Menu");

        lblWilayah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Wilayah.png"))); // NOI18N
        lblWilayah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblWilayahMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Wilayah");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/karyawan.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(61, 61, 61))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPelanggan)
                                    .addComponent(jLabel1)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(jLabel7)))
                        .addGap(99, 99, 99)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMenu)
                            .addComponent(lblTransaksi)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel9)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblWilayah)
                        .addGap(151, 151, 151))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(196, 196, 196))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMenu)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPelanggan)
                    .addComponent(lblTransaksi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWilayah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mnLogin.setText("File");

        mnLogout.setText("Logout");
        mnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLogoutActionPerformed(evt);
            }
        });
        mnLogin.add(mnLogout);

        jMenuBar1.add(mnLogin);

        jMenu6.setText("Laporan");

        MnLapKaryawan.setText("Laporan Karyawan");
        MnLapKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnLapKaryawanActionPerformed(evt);
            }
        });
        jMenu6.add(MnLapKaryawan);

        MnLapPelanggan.setText("Laporan Pelanggan");
        MnLapPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnLapPelangganActionPerformed(evt);
            }
        });
        jMenu6.add(MnLapPelanggan);

        MnLapWilayah.setText("Laporan Wilayah");
        MnLapWilayah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnLapWilayahActionPerformed(evt);
            }
        });
        jMenu6.add(MnLapWilayah);

        MnLapMenu.setText("Laporan Menu");
        MnLapMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnLapMenuActionPerformed(evt);
            }
        });
        jMenu6.add(MnLapMenu);

        MnLapDitempat.setText("Laporan Transaksi Ditempat");
        MnLapDitempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnLapDitempatActionPerformed(evt);
            }
        });
        jMenu6.add(MnLapDitempat);

        MnLapDelivery.setText("Laporan Transaksi Delivery");
        MnLapDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnLapDeliveryActionPerformed(evt);
            }
        });
        jMenu6.add(MnLapDelivery);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLogoutActionPerformed
     JOptionPane.showMessageDialog(null, "Anda Berhasil Logout");
     FormLogin form = new FormLogin();
     form.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_mnLogoutActionPerformed

    private void lblMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuMouseClicked
    FormMenuMakanan mn = new FormMenuMakanan();
    mn.setVisible(true);
    }//GEN-LAST:event_lblMenuMouseClicked

    private void lblPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPelangganMouseClicked
    FormPelanggan plgn = new FormPelanggan();
    plgn.setVisible(true);
    }//GEN-LAST:event_lblPelangganMouseClicked

    private void lblTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTransaksiMouseClicked
    FormPilihanPesan pil = new FormPilihanPesan();
    pil.setVisible(true);    
    }//GEN-LAST:event_lblTransaksiMouseClicked

    private void lblWilayahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblWilayahMouseClicked
        FormWilayah wl = new FormWilayah();
        wl.setVisible(true);
    }//GEN-LAST:event_lblWilayahMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
    FormKaryawan form = new FormKaryawan();
    form.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void MnLapKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnLapKaryawanActionPerformed
        try{
        KoneksiDB koneksi = new KoneksiDB();
        koneksi.getkoneksi();
        try{
        Map<String, Object> parameter = new HashMap<String, Object>();
        File rpt = new File ("src/Report/LaporanKaryawan.jrxml");
       JasperDesign jasDesign = JRXmlLoader.load(rpt);
        parameter.clear();
     JasperReport jasReport = JasperCompileManager.compileReport(jasDesign);
        JasperPrint jasPrint = JasperFillManager.fillReport(jasReport,
        parameter, koneksi.getkoneksi());
         JasperViewer.viewReport(jasPrint, false);
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Laporan Tidak Ditemukan"+e);
        }
        }catch(Exception e){
        JOptionPane.showConfirmDialog(null, e);}
    }//GEN-LAST:event_MnLapKaryawanActionPerformed

    private void MnLapPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnLapPelangganActionPerformed
     try{
        KoneksiDB koneksi = new KoneksiDB();
        koneksi.getkoneksi();
        try{
            Map<String, Object> parameter = new HashMap<String, Object>();
            File rpt = new File ("src/Report/LaporanPelanggan.jrxml");
            JasperDesign jasDesign = JRXmlLoader.load(rpt);
                parameter.clear();
                JasperReport jasReport = JasperCompileManager.compileReport(jasDesign);
                JasperPrint jasPrint = JasperFillManager.fillReport(jasReport,
                        parameter, koneksi.getkoneksi());
                JasperViewer.viewReport(jasPrint, false);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Laporan Tidak Ditemukan"+e);
        }
    }catch(Exception e){
        JOptionPane.showConfirmDialog(null, e);
    }
    }//GEN-LAST:event_MnLapPelangganActionPerformed

    private void MnLapWilayahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnLapWilayahActionPerformed
     try{
        KoneksiDB koneksi = new KoneksiDB();
        koneksi.getkoneksi();
        try{
            Map<String, Object> parameter = new HashMap<String, Object>();
            File rpt = new File ("src/Report/LaporanWilayah.jrxml");
            JasperDesign jasDesign = JRXmlLoader.load(rpt);
                parameter.clear();
     JasperReport jasReport = JasperCompileManager.compileReport(jasDesign);
      JasperPrint jasPrint = JasperFillManager.fillReport(jasReport,
                        parameter, koneksi.getkoneksi());
                JasperViewer.viewReport(jasPrint, false);
        }catch(Exception e){
    JOptionPane.showMessageDialog(null, "Laporan Tidak Ditemukan"+e);
        }
    }catch(Exception e){
        JOptionPane.showConfirmDialog(null, e);}
    }//GEN-LAST:event_MnLapWilayahActionPerformed

    private void MnLapMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnLapMenuActionPerformed
       try{
        KoneksiDB koneksi = new KoneksiDB();
        koneksi.getkoneksi();
        try{
            Map<String, Object> parameter = new HashMap<String, Object>();
            File rpt = new File ("src/Report/LaporanMenu.jrxml");
            JasperDesign jasDesign = JRXmlLoader.load(rpt);
         parameter.clear();
    JasperReport jasReport = JasperCompileManager.compileReport(jasDesign);
        JasperPrint jasPrint = JasperFillManager.fillReport(jasReport,
                        parameter, koneksi.getkoneksi());
                JasperViewer.viewReport(jasPrint, false);
        }catch(Exception e){
      JOptionPane.showMessageDialog(null, "Laporan Tidak Ditemukan"+e);
        }
    }catch(Exception e){
        JOptionPane.showConfirmDialog(null, e);}
    }//GEN-LAST:event_MnLapMenuActionPerformed

    private void MnLapDitempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnLapDitempatActionPerformed
         try{
        KoneksiDB koneksi = new KoneksiDB();
        koneksi.getkoneksi();
        try{
            Map<String, Object> parameter = new HashMap<String, Object>();
            File rpt = new File ("src/Report/NotaPembayaran.jrxml");
            JasperDesign jasDesign = JRXmlLoader.load(rpt);
                parameter.clear();
        JasperReport jasReport = JasperCompileManager.compileReport(jasDesign);
        JasperPrint jasPrint = JasperFillManager.fillReport(jasReport,
                        parameter, koneksi.getkoneksi());
                JasperViewer.viewReport(jasPrint, false);
                new Boolean(true);
        }catch(Exception e){
       JOptionPane.showMessageDialog(null, "Laporan Tidak Ditemukan"+e);
        }
    }catch(Exception e){
        JOptionPane.showConfirmDialog(null, e);}
    }//GEN-LAST:event_MnLapDitempatActionPerformed

    private void MnLapDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnLapDeliveryActionPerformed
          try{
        KoneksiDB koneksi = new KoneksiDB();
        koneksi.getkoneksi();
        try{
            Map<String, Object> parameter = new HashMap<String, Object>();
            File rpt = new File ("src/Report/NodePembayaran.jrxml");
            JasperDesign jasDesign = JRXmlLoader.load(rpt);
                parameter.clear();
      JasperReport jasReport = JasperCompileManager.compileReport(jasDesign);
        JasperPrint jasPrint = JasperFillManager.fillReport(jasReport,
                        parameter, koneksi.getkoneksi());
                JasperViewer.viewReport(jasPrint, false);
                new Boolean(true);
        }catch(Exception e){
      JOptionPane.showMessageDialog(null, "Laporan Tidak Ditemukan"+e);
        }
    }catch(Exception e){
        JOptionPane.showConfirmDialog(null, e);}
    }//GEN-LAST:event_MnLapDeliveryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MnLapDelivery;
    private javax.swing.JMenuItem MnLapDitempat;
    private javax.swing.JMenuItem MnLapKaryawan;
    private javax.swing.JMenuItem MnLapMenu;
    private javax.swing.JMenuItem MnLapPelanggan;
    private javax.swing.JMenuItem MnLapWilayah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblPelanggan;
    private javax.swing.JLabel lblTransaksi;
    private javax.swing.JLabel lblWilayah;
    private javax.swing.JMenu mnLogin;
    private javax.swing.JMenuItem mnLogout;
    // End of variables declaration//GEN-END:variables
}
